// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N = Integer.parseInt(args[0]);
		int i = 0;
		int bigger = 0;
		int smaller = 0;

		while(i < N){
			double number = Math.random();
			if(number > 0.5){
				bigger++;
			}
			else{
				smaller++;
			}
			i++;
		}

		System.out.println("> 0.5:  " + bigger);
		System.out.println("<= 0.5: " + smaller);
		
		if (bigger != 0 && smaller != 0){
			double ratio = (double) bigger / smaller;
			System.out.println("Ratio:  " + ratio);
		}
	}
}
